### ISSUE TITLE
Phát triển giao diện tin tức

### ISSUE THREAD

**Issue by HoangDe13** [HoangDe13/AppTourDuLich#12]

**Comment by hoanghuynh2000** [comment]
Tôi muốn có màn hình Tin Tức để hiển thị thông tin của các chuyến đi . cũng như là thông tin thời tiết của khu vực đó.

**Comment by hoanghuynh2000** [comment]
- Hiển thị các thông tin về các tour đã đi.
- hiển thị thông tin thời tiết các khu vực .
