### ISSUE TITLE
Phát triển giao diện cài đặt

### ISSUE THREAD

**Issue by HoangDe13** [HoangDe13/AppTourDuLich#13]

**Comment by hoanghuynh2000** [comment]
- [ ]  Thay đổi Ngôn ngữ trên ứng dụng
- [ ] Xem các điều khoản của ứng dụng
- [ ] Xem danh sách tour đã thích.
- [ ] Xem Lịch Sử Giao Dịch.
- [ ] Xem Thông tin liên hệ.\
