### ISSUE TITLE
Phát triển giao diện đã thích

### ISSUE THREAD

**Issue by HoangDe13** [HoangDe13/AppTourDuLich#17]

**Comment by hoanghuynh2000** [comment]
- [ ] Hiển thị các tour mà khách hàng chọn đã thích.
- [ ] Mất khi các tour đã đi hoặc khách hàng bỏ thích.

**Comment by hoanghuynh2000** [comment]
Cho phép khách hàng xem thông tin các tour khách hàng đã thích và có thể thực hiện chức năng thanh toán tour đó.
