### ISSUE TITLE
Phát triển giao diện đăng nhập / đăng kí

### ISSUE THREAD

**Issue by HoangDe13** [HoangDe13/AppTourDuLich#5]

**Comment by HoangDe13** [comment]
- [x]  Chức năng đăng nhập
- [x] Chức năng đăng kí thông tin khách hàng

**Comment by hoanghuynh2000** [comment]
Tôi muốn chức năng đăng nhập với tài khoản là số điện thoại và mật khẩu do người dùng tự đặt
Tôi muốn chức năng đăng kí phải có đầy đủ các thông tin khách hàng : Họ Tên , Số Điện Thoại, Địa Chỉ, Năm Sinh, Giới Tính .

**Comment by HoangDe13** [comment]
Đã hoàn thành
