### ISSUE TITLE
Phát triển giao diện Cá Nhân

### ISSUE THREAD

**Issue by HoangDe13** [HoangDe13/AppTourDuLich#7]

**Comment by hoanghuynh2000** [comment]
Tôi muốn có giao diện cá nhân hiển thị các thông tin của khách hàng, ảnh đại diện của khách hàng.
Tôi muốn giao diện cá nhân phải có chức năng cập nhật thông tin khách hàng.

**Comment by HoangDe13** [comment]
- [ ] Hiển thị Thông tin cá nhân khách hàng

**Comment by hoanghuynh2000** [comment]
Hoàn Thành
