### ISSUE TITLE
Phát triển giao diện chi tiết tour

### ISSUE THREAD

**Issue by HoangDe13** [HoangDe13/AppTourDuLich#9]

**Comment by hoanghuynh2000** [comment]
Tôi muốn sau khi chọn tour ở màn hình trang chủ ,sẽ hiển thị lên chi tiết thông tin, giá vé, phương tiện di chuyển, ngày khởi hành , ngày về của tour 
Tôi muốn có nút đặt chỗ ở màn hình chi tiết tour

**Comment by hoanghuynh2000** [comment]
- Hiển thị thông tin chi tiết của tour ( mô tả, phương tiện , khách sạn, giá vé,...)
- Chọn đặt tour khi cần thiết.
